### PR TITLE
Issue#11 pause menu

### LINKED ISSUE #11: Implement Pause Menu Feature
## Description

We need to add a pause menu to our game to enhance the user experience by allowing players to pause the game and access various options. The pause menu should be accessible at any point during gameplay and provide functionalities such as resuming the game, adjusting settings, and exiting to the main menu.

## Requirements

1. **Basic Functionality**:
    - The game should pause when the pause menu is activated, freezing all in-game actions.
    - The pause menu should be accessible through a designated button (e.g., the "Escape" key on the keyboard or a specific button on a game controller).

2. **Menu Options**:
    - **Resume**: Allows the player to close the pause menu and resume the game.
    - **Settings**: Provides access to game settings such as audio, video, and controls.
    - **Main Menu**: Allows the player to exit to the main menu.
    - **Quit Game**: Allows the player to exit the game entirely.

3. **Visual and Audio Feedback**:
    - Ensure the pause menu has a clear and intuitive layout with easily readable text and buttons.
    - Add audio feedback for menu interactions (e.g., button clicks).

4. **Settings Integration**:
    - Ensure any changes made in the settings menu are applied immediately or upon resuming the game.
    - Include settings options for adjusting audio levels, display settings, and control mappings.

## Tasks

- [x] Design and implement the basic pause menu structure.
- [x] Add functionality for the game to pause when the menu is activated.
- [x] Develop menu options: Resume, Settings, Main Menu, Quit Game.
- [x] Create visual layout and design for the pause menu.
- [x] Implement audio feedback for menu interactions.
- [x] Integrate settings menu with adjustable options.
- [x] Ensure the pause menu works correctly in various game states.

### PR DESCRIPTION
**Pull request by SykoDaedalus**
Added a pause menu to the game which is activated by pressing the  `Esc`  key.I thought of adding click sounds to button but decided to add it later stage
issue#11 pause menu

### CODE REVIEW

**Comment by SykoDaedalus** [comment]
@kmtGryffindor20  @darshi1337 please review

**Comment by lla-dane** [comment]
You could make the snow to fall continuously in the pause menu, would look much cooler. Could use a better font:).

**Comment by SykoDaedalus** [comment]
okay..shall i use the font that came with the project or any other would do? I tried to keep it true to the pixel style game has but found very few that worked.

**Comment by kmtGryffindor20** [comment]
Also add a settings button (need not work right now). Settings should be accessible through the pause menu too.

**Comment by SykoDaedalus** [comment]
> Also add a settings button (need not work right now). Settings should be accessible through the pause menu too.

alright

**Comment by SykoDaedalus** [comment]
Added some light snow in the bg as well changed the fonts (ugh, I had to settle it with this font, could not find any good pixel type) as well as a settings button
finalPausereview-ezgif com-video-to-gif-converter
@lla-dane @kmtGryffindor20

**Pull request merged**
