### PR TITLE
#issue8 implemented double jump

### PR DESCRIPTION
**Pull request by SykoDaedalus**
Added double jump

### CODE REVIEW

**Comment by SykoDaedalus** [comment]
@kmtGryffindor20 I have fixed the previous PR please review

**Comment by kmtGryffindor20** [comment]
It would be good if you add a condition where if the player jumps using the spring then they cannot do a double jump. Otherwise it works fine.

**Comment by SykoDaedalus** [comment]
Alright

**Comment by SykoDaedalus** [comment]
@kmtGryffindor20 please review the changes

**Comment by kmtGryffindor20** [comment]
Well the player can still double jump after launched by the spring. We can leave it as a feature or fix it later if needed. Merging this

**Pull request merged**
