### PR TITLE
Pause menu complete

### LINKED ISSUE #11: Implement Pause Menu Feature
## Description

We need to add a pause menu to our game to enhance the user experience by allowing players to pause the game and access various options. The pause menu should be accessible at any point during gameplay and provide functionalities such as resuming the game, adjusting settings, and exiting to the main menu.

## Requirements

1. **Basic Functionality**:
    - The game should pause when the pause menu is activated, freezing all in-game actions.
    - The pause menu should be accessible through a designated button (e.g., the "Escape" key on the keyboard or a specific button on a game controller).

2. **Menu Options**:
    - **Resume**: Allows the player to close the pause menu and resume the game.
    - **Settings**: Provides access to game settings such as audio, video, and controls.
    - **Main Menu**: Allows the player to exit to the main menu.
    - **Quit Game**: Allows the player to exit the game entirely.

3. **Visual and Audio Feedback**:
    - Ensure the pause menu has a clear and intuitive layout with easily readable text and buttons.
    - Add audio feedback for menu interactions (e.g., button clicks).

4. **Settings Integration**:
    - Ensure any changes made in the settings menu are applied immediately or upon resuming the game.
    - Include settings options for adjusting audio levels, display settings, and control mappings.

## Tasks

- [x] Design and implement the basic pause menu structure.
- [x] Add functionality for the game to pause when the menu is activated.
- [x] Develop menu options: Resume, Settings, Main Menu, Quit Game.
- [x] Create visual layout and design for the pause menu.
- [x] Implement audio feedback for menu interactions.
- [x] Integrate settings menu with adjustable options.
- [x] Ensure the pause menu works correctly in various game states.

### PR DESCRIPTION
**Pull request by SykoDaedalus**
added button click sounds and settings page @darshi1337 @kmtGryffindor20

### CODE REVIEW

**Comment by kmtGryffindor20** [comment]
image

There is a blank space above the settings options. On pressing the `Esc` you can still open and close the pause menu and it can be seen through this.

Also there is no function implemented for the Resolution Dropdown

**Comment by SykoDaedalus** [comment]
@kmtGryffindor20 I have fix the issues, should be fine now.

**Comment by lla-dane** [comment]
Falling snow, of random sizes and random speeds, in the pause menu would look pretty cool too.

**Comment by SykoDaedalus** [comment]
> Falling snow, of random sizes and random speeds, in the pause menu would look pretty cool too.

I have added falling snow in the pause menu, but the snow starts falling after a little delay because of the particle speed.


finalPausereview-ezgif com-video-to-gif-converter

**Comment by iwdie** [comment]
I had a similar problem, which I fixed by setting the Y position of the snow generator to 20, or lowering it as required per level. This worked for me.

**Comment by SykoDaedalus** [comment]
> I had a similar problem, which I fixed by setting the Y position of the snow generator to 20, or lowering it as required per level. This worked for me.

Thanks, will fix it today

**Comment by SykoDaedalus** [comment]
Tweaked some values and now snow should fall instantly in the pause menu

**Pull request merged**
