### PR TITLE
added Ice monster killing mechanism

### PR DESCRIPTION
**Pull request by iwdie**
https://github.com/lla-dane/Jack-in-the-wild/assets/42923352/4fbceeab-22e9-4fae-9882-77bdbed4b533

Tutorial level will introduce the player with controls.

### CODE REVIEW

**Comment by iwdie** [comment]
I checked , and the level got kind of broken due to switching branch, will fix it in later commits.

**Comment by lla-dane** [comment]
Looks good, could make a few upgrades like, darken the environment a little more and add lights on the street lamps or reduce the light radius in the lamps, would look more real. Could add fire lamps at the bridge. Add more things on the streets like animated grass and plants, increase the entropy here and there.

**Comment by iwdie** [comment]
> Looks good, could make a few upgrades like, darken the environment a little more and add lights on the street lamps or reduce the light radius in the lamps, would look more real. Could add fire lamps at the bridge. Add more things on the streets like animated grass and plants, increase the entropy here and there.

Thanks for the suggestions , will be working toward making these improvements :)

**Comment by iwdie** [comment]
https://github.com/lla-dane/Jack-in-the-wild/assets/42923352/07bf2b2e-2a30-463c-9c23-27efc9a30d68

I wanted to develop  an original mechanism to kill ice monster and make them look really cool and unkillable with normal attacks; So i tried this

**Comment by iwdie** [comment]
@kmtGryffindor20  I am not sure if  i should ditch  this idea or should i keep it? also i updated the game doc

**Comment by kmtGryffindor20** [comment]
> @kmtGryffindor20 I am not sure if i should ditch this idea or should i keep it? also i updated the game doc

It's fine... Just wanted to ask if you did any changes in the main Game.unity scene??  If not then revert the changes of that file to the previous state and commit your changes.

`git checkout main -- Assets/Scenes/Game.unity` should work fine if your main branch was upto date.

Checkout [this video](https://youtu.be/YUHS5Ana7Jw?si=Bw_acnq2BaS_ZBdo) if you have any issues.

**Comment by iwdie** [comment]
git1
I did add the parallax effect to the Game.unity scene in the starting , but no big changes.

**Comment by kmtGryffindor20** [comment]
The levels are not fully designed yet... I assume you are going to do that in later pull requests... Thus merging it here

**Pull request merged**
