### PR TITLE
implemented a basic main-menu and also respawn mechanism

### PR DESCRIPTION
**Pull request by SykoDaedalus**
implemented a basic main-menu with options page yet to be implemented. Also adjusted the spawn mechanism
Screenshot 2024-06-01 001926

### CODE REVIEW

**Comment by kmtGryffindor20** [comment]
Multiple canvases are not preferred to be used unless necessary. The options menu could have just been done using another panel.

Also the menu scene opens with the options menu. Make it so that the main menu is at the start.

While you're at it also change the way the lives are shown in the HUD. The positioning can be changed.

Also when all lives end, 
image

This happens where the player just lies down facing the floor and cannot move. It can be made into a new issue but if you can fix it do it too.

**Comment by SykoDaedalus** [comment]
okay, will implement the suggestions

**Comment by SykoDaedalus** [comment]
@kmtGryffindor20  I have done the changes please review

**Comment by kmtGryffindor20** [comment]
image

It looks good. But is outside the Canvas thus is not properly visible in the game view.

Also the Play button is not working properly. That is most probably because the script is name `menu` instead of `Menu`.
This sometimes result in `No MonoBehaviour scripts in the file, or their names do not match the file name.`
 Always name the script and the class in PascalCase.

**Comment by kmtGryffindor20** [comment]
Closing this as it is redundant. The changes are already applied through another PR

**Pull request closed without merging**
